/* (c) 2019 Confio UO. Licensed under Apache-2.0 */

#ifndef cosmwasm_h
#define cosmwasm_h

/* Generated with cbindgen:0.9.1 */

/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

typedef struct Buffer {
  uint8_t *ptr;
  uintptr_t len;
  uintptr_t cap;
} Buffer;

typedef struct db_t {

} db_t;

typedef struct DB {
  db_t *state;
  int64_t (*c_get)(db_t*, Buffer, Buffer);
  void (*c_set)(db_t*, Buffer, Buffer);
} DB;

int32_t add(int32_t a, int32_t b);

Buffer db_access(DB db, Buffer key, Buffer *err);

/**
 * divide returns the rounded (i32) result, returns a C error if div == 0
 */
int32_t divide(int32_t num, int32_t div, Buffer *err);

void free_rust(Buffer buf);

Buffer greet(Buffer name);

Buffer may_panic(int32_t guess, Buffer *err);

#endif /* cosmwasm_h */
